// Payment Options
export const LoanTypeOptions = [
  // 🧍‍♂️ Personal & Household
  { value: "personal", label: "ব্যক্তিগত ঋণ" },
  { value: "household", label: "গৃহস্থালী ঋণ" },
  { value: "marriage", label: "বিবাহ ঋণ" },
  { value: "education", label: "শিক্ষা ঋণ" },
  { value: "medical", label: "চিকিৎসা ঋণ" },
  { value: "travel", label: "ভ্রমণ ঋণ" },
  { value: "festival", label: "উৎসব ঋণ (ঈদ, পূজা ইত্যাদি)" },
  { value: "emergency", label: "জরুরি ঋণ" },
  { value: "renovation", label: "বাড়ি সংস্কার ঋণ" },
  { value: "housing", label: "বাসস্থান ঋণ" },
  { value: "vehicle", label: "যানবাহন ক্রয় ঋণ" },
  { value: "land_purchase", label: "জমি ক্রয় ঋণ" },
  { value: "appliance_purchase", label: "ইলেকট্রনিক্স ক্রয় ঋণ" },
  { value: "repayment", label: "পুরনো ঋণ পরিশোধ ঋণ" },

  // 💼 Business & Trade
  { value: "business", label: "ব্যবসায়িক ঋণ" },
  { value: "small_business", label: "ক্ষুদ্র ব্যবসা ঋণ" },
  { value: "medium_business", label: "মাঝারি ব্যবসা ঋণ" },
  { value: "retail", label: "খুচরা ব্যবসা ঋণ" },
  { value: "wholesale", label: "পাইকারি ব্যবসা ঋণ" },
  { value: "startup", label: "স্টার্টআপ ঋণ" },
  { value: "trade_license", label: "ট্রেড লাইসেন্স ভিত্তিক ঋণ" },
  { value: "ecommerce", label: "ই-কমার্স ব্যবসা ঋণ" },
  { value: "export_import", label: "রপ্তানি ও আমদানি ঋণ" },
  { value: "service_business", label: "সার্ভিস ব্যবসা ঋণ" },
  { value: "manufacturing", label: "উৎপাদন শিল্প ঋণ" },
  { value: "equipment", label: "যন্ত্রপাতি ক্রয় ঋণ" },
  { value: "warehouse", label: "গুদাম নির্মাণ ঋণ" },
  { value: "franchise", label: "ফ্র্যাঞ্চাইজি ব্যবসা ঋণ" },
  { value: "women_entrepreneur", label: "নারী উদ্যোক্তা ঋণ" },
  { value: "youth_entrepreneur", label: "যুব উদ্যোক্তা ঋণ" },

  // 🌾 Agriculture & Rural
  { value: "agriculture", label: "কৃষি ঋণ" },
  { value: "crop", label: "ফসল চাষ ঋণ" },
  { value: "livestock", label: "পশুপালন ঋণ" },
  { value: "poultry", label: "পোল্ট্রি ফার্ম ঋণ" },
  { value: "fisheries", label: "মৎস্য চাষ ঋণ" },
  { value: "dairy", label: "দুধ উৎপাদন ঋণ" },
  { value: "agro_equipment", label: "কৃষি যন্ত্রপাতি ঋণ" },
  { value: "seed", label: "বীজ ক্রয় ঋণ" },
  { value: "fertilizer", label: "সার ক্রয় ঋণ" },
  { value: "irrigation", label: "সেচ ঋণ" },
  { value: "seasonal", label: "ঋতুভিত্তিক কৃষি ঋণ" },

  // 🏗️ Infrastructure & Development
  { value: "construction", label: "নির্মাণ ঋণ" },
  { value: "real_estate", label: "রিয়েল এস্টেট ঋণ" },
  { value: "land_development", label: "জমি উন্নয়ন ঋণ" },
  { value: "solar", label: "সোলার এনার্জি ঋণ" },
  { value: "renewable_energy", label: "নবায়নযোগ্য জ্বালানি ঋণ" },
  { value: "environmental", label: "পরিবেশবান্ধব প্রকল্প ঋণ" },
  { value: "ngo_project", label: "এনজিও প্রকল্প ঋণ" },
  { value: "microfinance", label: "মাইক্রোফাইন্যান্স ঋণ" },

  // 💰 Special & Institutional
  { value: "salary_advance", label: "বেতন অগ্রিম ঋণ" },
  { value: "pension", label: "পেনশনভোগী ঋণ" },
  { value: "govt_employee", label: "সরকারি কর্মচারী ঋণ" },
  { value: "non_govt_employee", label: "বেসরকারি কর্মচারী ঋণ" },
  { value: "ngo_member", label: "এনজিও সদস্য ঋণ" },
  { value: "religious_institution", label: "ধর্মীয় প্রতিষ্ঠান ঋণ" },
  { value: "education_institution", label: "শিক্ষা প্রতিষ্ঠান ঋণ" },
  { value: "community_project", label: "কমিউনিটি উন্নয়ন ঋণ" },
];